// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2_BX4qiX5VpctoyPdUMM_cWWUiHYMTvo',
    appId: '1:650251146999:android:22917ad724bbdcbd93e5f2',
    messagingSenderId: '650251146999',
    projectId: 'testautenticacion-d586b',
    storageBucket: 'testautenticacion-d586b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzh6wZ14Z7TyewUtDdN0TVBl7MOt-wSBc',
    appId: '1:650251146999:web:f72a79b439da09f693e5f2',
    messagingSenderId: '650251146999',
    projectId: 'testautenticacion-d586b',
    authDomain: 'testautenticacion-d586b.firebaseapp.com',
    storageBucket: 'testautenticacion-d586b.firebasestorage.app',
    measurementId: 'G-JV2GPD9JWM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtR0RinHqtxp2kFgLv1gMjAoDMzyUbRW8',
    appId: '1:650251146999:ios:7edc3de4c22b35f593e5f2',
    messagingSenderId: '650251146999',
    projectId: 'testautenticacion-d586b',
    storageBucket: 'testautenticacion-d586b.firebasestorage.app',
    iosBundleId: 'com.Carlos.test',
  );

}